services:
  commercify-web:
    # image: ghcr.io/zenfulcode/commercifyweb:dev
    container_name: commercify-web
    build:
      context: .
      args:
        - NODE_ENV=production
        - NEXT_PUBLIC_COMMERCIFY_API_URL=http://localhost:6091/api/v1
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_COMMERCIFY_API_URL=${NEXT_PUBLIC_COMMERCIFY_API_URL}
      - NEXT_PUBLIC_DEV_COMMERCIFY_API_URL=${NEXT_PUBLIC_DEV_COMMERCIFY_API_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_DEV=${EMAIL_DEV}
    ports:
      - "3000:3000"
    networks:
      - commercify

  commercify-api:
    image: ghcr.io/zenfulcode/commercify:main
    env_file: .env
    container_name: commercify-api
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MOBILEPAY_MERCHANT_ID=${MOBILEPAY_MERCHANT_ID}
      - MOBILEPAY_CLIENT_ID=${MOBILEPAY_CLIENT_ID}
      - MOBILEPAY_CLIENT_SECRET=${MOBILEPAY_CLIENT_SECRET}
      - MOBILEPAY_SUBSCRIPTION_KEY=${MOBILEPAY_SUBSCRIPTION_KEY}
      - MOBILEPAY_API_URL=${MOBILEPAY_API_URL}
      - MOBILEPAY_SYSTEM_NAME=${MOBILEPAY_SYSTEM_NAME}
      - STRIPE_SECRET_TEST_KEY=${STRIPE_SECRET_TEST_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    ports:
      - "6091:6091"
    networks:
      - commercify

networks:
  commercify:
    driver: bridge
