services:
  commercify:
    image: ghcr.io/zenfulcode/commercify:dev
    env_file: .env
    container_name: commercify-backend
    ports:
      - "6091:6091"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MOBILEPAY_MERCHANT_ID=${MOBILEPAY_MERCHANT_ID}
      - MOBILEPAY_CLIENT_ID=${MOBILEPAY_CLIENT_ID}
      - MOBILEPAY_CLIENT_SECRET=${MOBILEPAY_CLIENT_SECRET}
      - MOBILEPAY_SUBSCRIPTION_KEY=${MOBILEPAY_SUBSCRIPTION_KEY}
      - MOBILEPAY_API_URL=${MOBILEPAY_API_URL}
      - MOBILEPAY_SYSTEM_NAME=${MOBILEPAY_SYSTEM_NAME}
      - STRIPE_SECRET_TEST_KEY=${STRIPE_SECRET_TEST_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - FRONTEND_URL=${FRONTEND_URL}
